[[manager.prepend_keymap]]
on = "M"
run = "plugin mount"

[[manager.prepend_keymap]]
on = ["E"]
run = "plugin eza-preview"
desc = "Toggle tree/list dir preview"

[[manager.prepend_keymap]]
on = ["+"]
run = "plugin eza-preview -- '--inc-level'"
desc = "Increment tree level"

[[manager.prepend_keymap]]
on = ["="]
run = "plugin eza-preview -- '--dec-level'"
desc = "Decrement tree level"

[[manager.prepend_keymap]]
on = ["$"]
run = "plugin eza-preview -- '--toggle-follow-symlinks'"
desc = "Toggle tree follow symlinks"

[[manager.prepend_keymap]]
on = ["b", "t"]
run = "plugin dual-pane toggle"
desc = "Dual-pane: toggle"

[[manager.prepend_keymap]]
on = ["b", "b"]
run = "plugin dual-pane toggle_zoom"
desc = "Dual-pane: toggle zoom"

[[manager.prepend_keymap]]
on = "<Tab>"
run = "plugin dual-pane next_pane"
desc = "Dual-pane: switch to the other pane"

[[manager.prepend_keymap]]
on = "["
run = "plugin dual-pane 'tab_switch -1 --relative'"
desc = "Dual-pane: switch active to previous tab"

[[manager.prepend_keymap]]
on = "]"
run = "plugin dual-pane 'tab_switch 1 --relative'"
desc = "Dual-pane: switch active to next tab"

[[manager.prepend_keymap]]
on = "1"
run = "plugin dual-pane 'tab_switch 0'"
desc = "Switch to the first tab"

[[manager.prepend_keymap]]
on = "2"
run = "plugin dual-pane 'tab_switch 1'"
desc = "Switch to the second tab"

[[manager.prepend_keymap]]
on = "3"
run = "plugin dual-pane 'tab_switch 2'"
desc = "Switch to the third tab"

[[manager.prepend_keymap]]
on = "4"
run = "plugin dual-pane 'tab_switch 3'"
desc = "Switch to the fourth tab"

[[manager.prepend_keymap]]
on = "5"
run = "plugin dual-pane 'tab_switch 4'"
desc = "Switch to the fifth tab"

[[manager.prepend_keymap]]
on = "6"
run = "plugin dual-pane 'tab_switch 5'"
desc = "Switch to the sixth tab"

[[manager.prepend_keymap]]
on = "7"
run = "plugin dual-pane 'tab_switch 6'"
desc = "Switch to the seventh tab"

[[manager.prepend_keymap]]
on = "8"
run = "plugin dual-pane 'tab_switch 7'"
desc = "Switch to the eighth tab"

[[manager.prepend_keymap]]
on = "9"
run = "plugin dual-pane 'tab_switch 8'"
desc = "Switch to the ninth tab"

[[manager.prepend_keymap]]
on = "t"
run = "plugin dual-pane 'tab_create --current'"
desc = "Dual-pane: create a new tab with CWD"

[[manager.prepend_keymap]]
on = "<F5>"
run = "plugin dual-pane 'copy_files --follow'"
desc = "Dual-pane: copy selected files from active to inactive pane"

[[manager.prepend_keymap]]
on = "<F6>"
run = "plugin dual-pane 'move_files --follow'"
desc = "Dual-pane: move selected files from active to inactive pane"

[[manager.prepend_keymap]]
on = ["b", "s"]
run = "plugin dual-pane save_config"
desc = "Dual-pane: save current configuration"

[[manager.prepend_keymap]]
on = ["b", "l"]
run = "plugin dual-pane load_config"
desc = "Dual-pane: load saved configuration"

[[manager.prepend_keymap]]
on = ["b", "r"]
run = "plugin dual-pane reset_config"
desc = "Dual-pane: reset saved configuration"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = "<C-1>"
run = "plugin toggle-view parent"
desc = "Toggle parent"

[[manager.prepend_keymap]]
on = "<C-2>"
run = "plugin toggle-view current"
desc = "Toggle current"

[[manager.prepend_keymap]]
on = "<C-3>"
run = "plugin toggle-view preview"
desc = "Toggle preview"

# Unyank
[[manager.prepend_keymap]]
on = "u"
run = "unyank"
desc = "Cancel the yank status"

#Archive
[[manager.prepend_keymap]]
on = ["l"]
run = "plugin fuse-archive mount"
desc = "Enter or Mount selected archive"

[[manager.prepend_keymap]]
on = ["<Right>"]
run = "plugin fuse-archive mount"
desc = "Enter or Mount selected archive"

[[manager.prepend_keymap]]
on = ["h"]
run = "plugin fuse-archive unmount"
desc = "Leave or Unmount selected archive"

[[manager.prepend_keymap]]
on = ["<Left>"]
run = "plugin fuse-archive unmount"
desc = "Leave or Unmount selected archive"

[[manager.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"

# Use K to move up in the parent directory
[[manager.prepend_keymap]]
on = ["K"]
run = ["leave", "arrow -1", "enter"]
desc = "Move up in the parent directory"


# Use J to move down in the parent directory
[[manager.prepend_keymap]]
on = ["J"]
run = ["leave", "arrow 1", "enter"]
desc = "Move down in the parent directory"

[[manager.prepend_keymap]]
on = ["P"]
run = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch zip"
desc = "Compress with ouch"

# Linemode
[[manager.prepend_keymap]]
on = ["n", "s"]
run = "linemode size"
desc = "Linemode: size"

[[manager.prepend_keymap]]
on = ["n", "p"]
run = "linemode permissions"
desc = "Linemode: permissions"

[[manager.prepend_keymap]]
on = ["n", "b"]
run = "linemode btime"
desc = "Linemode: btime"

[[manager.prepend_keymap]]
on = ["n", "m"]
run = "linemode mtime"
desc = "Linemode: mtime"

[[manager.prepend_keymap]]
on = ["n", "o"]
run = "linemode owner"
desc = "Linemode: owner"

[[manager.prepend_keymap]]
on = ["n", "n"]
run = "linemode none"
desc = "Linemode: none"

# shell
[[manager.prepend_keymap]]
on = "!"
run = 'shell --block -- $SHELL'
desc = "Open shell here"

# editor
[[manager.prepend_keymap]]
on = "e"
run = 'shell --block -- $EDITOR "$@"'
desc = "Open file in editor"

# viewer
[[manager.prepend_keymap]]
on = "i"
run = 'shell --block -- viewer.sh "$@"'
desc = "Open file in viewer"

# bookmarks
[[manager.prepend_keymap]]
on = ["m"]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"
