[manager]
show_symlink = false

[opener]
view = [
  { run = 'viewer.sh "$@"', desc = "View", block = true, for = "unix" },
  { run = 'code "%*"', orphan = true, desc = "code", for = "windows" },
  { run = 'code -w "%*"', block = true, desc = "code (block)", for = "windows" },
]

[open]
rules = [
  { name = "*/", use = [
    "edit",
    "open",
    "reveal",
  ] },

  { mime = "text/*", use = [
    "edit",
    "view",
    "reveal",
  ] },
  { mime = "image/*", use = [
    "open",
    "view",
    "reveal",
  ] },
  { mime = "{audio,video}/*", use = [
    "play",
    "reveal",
  ] },
  { mime = "inode/x-empty", use = [
    "edit",
    "view",
    "reveal",
  ] },

  { mime = "application/{,g}zip", use = [
    "extract",
    "reveal",
  ] },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [
    "extract",
    "reveal",
  ] },

  { mime = "application/json", use = [
    "edit",
    "view",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "view",
    "reveal",
  ] },

  { mime = "*", use = [
    "open",
    "view",
    "reveal",
  ] },
]

[plugin]

prepend_previewers = [
  # Djvu
  { mime = "image/vnd.djvu", run = "djvutxt-preview" },
  # PDF
  { mime = "application/pdf", run = "pdftotext-preview" },
  # Archive 
  # { mime = "application/*zip", run = "ouch" },
  # { mime = "application/x-{tar,bzip2,7z-compressed,rar,xz}", run = "ouch" },
  # Audio 
  { mime = "audio/*", run = "exifaudio" },
  # Torrent 
  { mime = "application/x-bittorrent", run = "torrent-preview" },
  # Docx
  { mime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document", run = "docx-preview" },
  # { name = "*.csv", run = "rich-preview" },                                                                   # for csv files
  { mime = "text/csv", run = "miller" },
  # { name = "*.md", run = "rich-preview" },    # for markdown (.md) files
  { name = "*.md", run = "glow" },            # for markdown (.md) files
  { name = "*.ipynb", run = "rich-preview" }, # for jupyter notebooks (.ipynb)
  { name = "*.json", run = "rich-preview" },  # for json (.json) files
  #    { name = "*.lang_type", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.
]
