[manager]
show_symlink   = false

[plugin]
preloaders = [
	{ name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
]

previewers = [
	{ name = "*/", run = "folder", sync = true },
	# Code
	{ mime = "text/*", run = "code" },
	{ mime = "*/{xml,javascript,x-wine-extension-ini}", run = "code" },
	# JSON
	{ mime = "application/json", run = "json" },
	# Djvu
	{ mime = "image/vnd.djvu", run = "djvutxt-preview" },
	# PDF
	{ mime = "application/pdf", run = "pdftotext-preview" },
# Markdown 
  { name = "*.md", run = "glow" },
	# Archive 
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-{tar,bzip2,7z-compressed,rar,xz}", run = "ouch" },
  # Audio 
  { mime = "audio/*",                     run = "exifaudio"},
  # Torrent 
  { mime = "application/x-bittorrent",    run = "torrent-preview"},
  # Docx
  { mime ="application/vnd.openxmlformats-officedocument.wordprocessingml.document", run = "docx-preview"},
  # CSV
  { mime = "text/csv", run = "miller"},
  # Fallback
	{ name = "*", run = "file" },
] 
