[manager]
show_symlink   = false

[opener]
view = [
	{ run = 'viewer.sh "$@"', desc = "View", block = true, for = "unix" },
	{ run = 'code "%*"',    orphan = true, desc = "code",         for = "windows" },
	{ run = 'code -w "%*"', block = true,  desc = "code (block)", for = "windows" },
]
edit = [
	{ run = '${EDITOR:=vi} "$@"', desc = "Edit", block = true, for = "unix" },
	{ run = 'code "%*"',    orphan = true, desc = "code",         for = "windows" },
	{ run = 'code -w "%*"', block = true,  desc = "code (block)", for = "windows" },
]
open = [
	{ run = 'xdg-open "$@"',                desc = "Open", for = "linux" },
	{ run = 'open "$@"',                    desc = "Open", for = "macos" },
	{ run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
	{ run = 'xdg-open "$(dirname "$0")"',            desc = "Reveal", for = "linux" },
	{ run = 'open -R "$1"',                          desc = "Reveal", for = "macos" },
	{ run = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
	{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
	{ run = 'unar "$1"', desc = "Extract here", for = "unix" },
	{ run = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
	{ run = 'mpv "%1"', orphan = true, for = "windows" },
	{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ mime = "text/*",          use = [ "edit", "view", "reveal" ] },
	{ mime = "image/*",         use = [ "open", "view", "reveal" ] },
	{ mime = "{audio,video}/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty",   use = [ "edit", "view", "reveal" ] },

	{ mime = "application/*zip", use = [ "extract", "reveal" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "view", "reveal" ] },
	{ mime = "*/javascript",     use = [ "edit", "view", "reveal" ] },

	{ mime = "*", use = [ "open", "view", "reveal" ] },
]

[plugin]
preloaders = [
	{ name = "*", cond = "!mime", run = "mime", multi = true, prio = "high" },
]

previewers = [
	{ name = "*/", run = "folder", sync = true },
	# Code
	{ mime = "text/*", run = "code" },
	{ mime = "*/{xml,javascript,x-wine-extension-ini}", run = "code" },
	# JSON
	{ mime = "application/json", run = "json" },
	# Djvu
	{ mime = "image/vnd.djvu", run = "djvutxt-preview" },
	# PDF
	{ mime = "application/pdf", run = "pdftotext-preview" },
# Markdown 
  { name = "*.md", run = "glow" },
	# Archive 
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-{tar,bzip2,7z-compressed,rar,xz}", run = "ouch" },
  # Audio 
  { mime = "audio/*",                     run = "exifaudio"},
  # Torrent 
  { mime = "application/x-bittorrent",    run = "torrent-preview"},
  # Docx
  { mime ="application/vnd.openxmlformats-officedocument.wordprocessingml.document", run = "docx-preview"},
  # CSV
  { mime = "text/csv", run = "miller"},
  # Fallback
	{ name = "*", run = "file" },
] 
