[sftp.rpi]
host     = "rpi.local"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"

[sftp.mac]
host     = "macbook.local"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"

[sftp.mini]
host     = "macmini.local"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"

[sftp.work]
host     = "work"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"
