[plugin]
prepend_previewers = [
  { name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { name = "*.doc", run = 'piper -- antiword "$1"' },
  # { name = "*.docx", run = 'piper -- docx2txt "$1" -' },
  { name = "*.docx", run = 'piper -- doxx --export text "$1"' },
  { mime = "application/{*zip,tar,bzip*,7z-compressed,xz,rar}", run = 'piper --format=url -- ouch l -t -y "$1"' },
  { name = "*.djvu", run  = "djvu-view"},
]

[opener]
edit = [
  { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
  { run = "nvim %*", block = true, for = "windows" },
]

