[[manager.prepend_keymap]]
on = "<C-d>"
run = "plugin diff"
desc = "Diff the selected with the hovered file"

[[manager.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"

[[manager.prepend_keymap]]
on = ["B"]
run = "plugin bookmarks --args=save"
desc = "Save current position as a bookmark"

[[manager.prepend_keymap]]
on = ["'"]
run = "plugin bookmarks --args=jump"
desc = "Jump to a bookmark"

[[manager.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks --args=delete"
desc = "Delete a bookmark"

[[manager.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks --args=delete_all"
desc = "Delete all bookmarks"

# Use the augmented arrow up command for the k key
[[manager.prepend_keymap]]
on = ["k"]
run = "plugin augment-command --args='arrow -1'"
desc = "Move cursor up"


# Use the augmented arrow down command for the j key
[[manager.prepend_keymap]]
on = ["j"]
run = "plugin augment-command --args='arrow 1'"
desc = "Move cursor down"


# Use K to move up in the parent directory
[[manager.prepend_keymap]]
on = ["K"]
run = "plugin augment-command --args='parent-arrow -1'"
desc = "Move cursor up in the parent directory"


# Use J to move down in the parent directory
[[manager.prepend_keymap]]
on = ["J"]
run = "plugin augment-command --args='parent-arrow 1'"
desc = "Move cursor down in the parent directory"


# Use the augmented enter command for the l key
[[manager.prepend_keymap]]
on = ["l"]
run = "plugin augment-command --args='enter'"
desc = "Enter the child directory, or open the file"


# Use the augmented enter command for the <Enter> key
[[manager.prepend_keymap]]
on = ["<Enter>"]
run = "plugin augment-command --args='enter'"
desc = "Enter the child directory, or open the file"


# Use the augmented enter command for the <S-Enter> key
[[manager.prepend_keymap]]
on = ["<S-Enter>"]
run = "plugin augment-command --args='enter --interactive'"
desc = "Enter the child directory, or open the file interactively"


# Use the augmented enter command for the <Right> key
# but without skipping directories
[[manager.prepend_keymap]]
on = ["<Right>"]
run = "plugin augment-command --args='enter --no-skip'"
desc = "Enter the child directory, or open the file"


# Use the augmented leave command for the h key
[[manager.prepend_keymap]]
on = ["h"]
run = "plugin augment-command --args='leave'"
desc = "Go back to the parent directory"


# Use the augmented leave command for the <Left> key
# but without skipping directories
[[manager.prepend_keymap]]
on = ["<Left>"]
run = "plugin augment-command --args='leave --no-skip'"
desc = "Go back to the parent directory"

# Seeking
[[manager.prepend_keymap]]
on = ["<C-j>"]
run = "seek 5"
desk = "Seek down 5 units in the preview"

[[manager.prepend_keymap]]
on = ["<C-k>"]
run = "seek -5"
desk = "Seek up 5 units in the preview"

# Use the augmented open to open files interactively with O
[[manager.prepend_keymap]]
on = ["O"]
run = "plugin augment-command --args='open --interactive'"
desc = "Open selected files interactively"


# Use u to unselect and unyank all files
[[manager.prepend_keymap]]
on = ["u"]
run = ["select_all --state=false", "unyank"]
desc = "Unselect all files and also unyank cut files"


# Use p to paste files
[[manager.prepend_keymap]]
on = ["p"]
run = "plugin augment-command --args='paste'"
desc = "Paste the files"


# Use P to paste files and
# overwrite the destination file if it exists
[[manager.prepend_keymap]]
on = ["P"]
run = "plugin augment-command --args='paste --force'"
desc = "Paste the files (overwrite if the destination exists)"


# Use d to move files to the trash
[[manager.prepend_keymap]]
on = ["d"]
run = "plugin augment-command --args='remove'"
desc = "Move the files to the trash"


# Use D to delete files permanently
[[manager.prepend_keymap]]
on = ["D"]
run = "plugin augment-command --args='remove --permanently'"
desc = "Permanently delete the files"

# Use e to open files using the editor
[[manager.prepend_keymap]]
on = ["e"]
run = "plugin augment-command --args='editor'"
desc = "Open files with the default editor"

# Use i to open files using the viewer.sh
[[manager.prepend_keymap]]
on = ["i"]
run = '''plugin augment-command --args="shell 'viewer.sh $@' --block --confirm"'''
desc = "Open the viewer"

# Use r to rename files with the cursor before the file extension
[[manager.prepend_keymap]]
on = ["r"]
run = "plugin augment-command --args='rename --cursor=before_ext'"
desc = "Rename a file or directory"


# Use R to remove the whole file name when renaming
[[manager.prepend_keymap]]
on = ["R"]
run = "plugin augment-command --args='rename --empty=all'"
desc = "Rename file and remove the whole file name"

[[manager.prepend_keymap]]
on = ["<Backspace>"]
run = 'back'
desc = "Go back to the previous directory"

[[manager.prepend_keymap]]
on = ["!"]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["T", "H"]
run = "plugin --sync hide-preview"
desc = "Hide preview pane"

[[manager.prepend_keymap]]
on = ["T", "M"]
run = "plugin --sync max-preview"
desc = "Max preview pane"
