[input]
prepend_keymap = [{ on = "<Esc>", run = "close", desc = "Cancel input" }]

[mgr]
prepend_keymap = [
  # Smart-enter
  # { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

  # Mount
  { on = [ "M","M"], run = "plugin mount", desc = "Mount drive", for = 'unix' },
  # SSHFS
  { on = ["M","m"], run = "plugin sshfs -- mount --jump",    desc = "Mount & jump" },
  { on = ["M","u"], run = "plugin sshfs -- unmount",         desc = "Unmount SSHFS" },
  { on = ["M","j"], run = "plugin sshfs -- jump",            desc = "Jump to mount" },
  { on = ["M","a"], run = "plugin sshfs -- add",             desc = "Add SSH host" },
  { on = ["M","r"], run = "plugin sshfs -- remove",          desc = "Remove SSH host" },
  { on = ["M","h"], run = "plugin sshfs -- home",            desc = "Go to mount home" },
  { on = ["M","c"], run = "cd ~/.ssh/",                      desc = "Go to ssh config" },

  # Go to 
  { on = [ "g","c" ], run = "cd ~/.config", desc = "Go ~/.config", for = 'unix' },
  { on = [ "g","c" ], run = "cd ~/AppData/Roaming", desc = "Go ~/.config", for = 'windows' },
  { on = [ "g","H" ], run = "cd C:/Mac/Home", desc = "Go Mac Home", for = 'windows' },

  # Unyank
  { on = "u", run = "unyank", desc = "Cancel the yank status" },

  # Shell
  { on = "!", run = 'shell --block -- $SHELL', desc = "Open shell here", for = 'unix' },
  { on = "!", run = 'shell --block -- "bash.exe"', desc = "Open shell here", for = 'windows' },

  # Viewer
  { on = "i", run = 'shell --block -- viewer.zsh "$@"', desc = "Open file in viewer", for = 'unix' },

  # Chmod
  { on = [ "c","m" ], run = "plugin chmod", desc = "Chmod on selected files", for = 'unix' },
  
  # Compress
  { on   = [ "c", "a", "a" ], run  = "plugin compress", desc = "Archive selected files" },
  { on   = [ "c", "a", "p" ], run  = "plugin compress -p", desc = "Archive selected files (password)" },
  { on   = [ "c", "a", "h" ], run  = "plugin compress -ph", desc = "Archive selected files (password+header)" },
  { on   = [ "c", "a", "l" ], run  = "plugin compress -l", desc = "Archive selected files (compression level)" },
  { on   = [ "c", "a", "u" ], run  = "plugin compress -phl", desc = "Archive selected files (password+header+level)" },

  # Toggle-pane
  { on = [ "T","1" ], run = "plugin toggle-pane min-parent", desc = "Show or hide the parent pane" },
  { on = [ "T","!" ], run = "plugin toggle-pane max-parent", desc = "Maximize or restore the parent pane" },
  { on = [ "T","2" ], run = "plugin toggle-pane min-current", desc = "Show or hide the current pane" },
  { on = [ "T","@" ], run = "plugin toggle-pane max-current", desc = "Maximize or restore the current pane" },
  { on = [ "T","3" ], run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
  { on = [ "T","#" ], run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },

  # Smart filter
  { on   = "F", run  = "plugin smart-filter", desc = "Smart filter"},

  # fuse-archive
  { on   = [ "<Enter>" ], run = "plugin fuse-archive -- mount", desc = "Enter or Mount selected archive" },
  { on   = [ "<Right>" ], run = "plugin fuse-archive -- mount", desc = "Enter or Mount selected archive" },
  { on   = [ "<Left>" ], run = "plugin fuse-archive -- leave", desc = "Leave selected archive without unmount it" },
  { on   = [ "l" ], run = "plugin fuse-archive -- mount", desc = "Enter or Mount selected archive" },
  { on   = [ "h" ], run = "plugin fuse-archive -- leave", desc = "Leave selected archive without unmount it" },

    # Over quit command for yazi <= v25.5.31 to unmount on quit. For nightly yazi, you don't need to add these lines.
    { on   = [ "q" ], run = ["plugin fuse-archive -- unmount", "quit"], desc = "Quit the process" },
    { on   = [ "Q" ], run = ["plugin fuse-archive -- unmount", "quit --no-cwd-file"], desc = "Quit without outputting cwd-file" },

    # bookmarks
  { on = "[", run = "plugin whoosh jump_by_key", desc = "Jump bookmark by key" },
  { on = "}", run = "plugin whoosh fuzzy", desc = "Direct fuzzy search for bookmarks" },
  { on = [ "]", "a" ], run = "plugin whoosh save", desc = "Add bookmark (hovered file/directory)" },
  { on = [ "]", "A" ], run = "plugin whoosh save_cwd", desc = "Add bookmark (current directory)" },
  { on = [ "]", "t" ], run = "plugin whoosh save_temp", desc = "Add temporary bookmark (hovered file/directory)" },
  { on = [ "]", "T" ], run = "plugin whoosh save_cwd_temp", desc = "Add temporary bookmark (current directory)" },
  { on = [ "]", "f" ], run = "plugin whoosh jump_by_fzf", desc = "Jump bookmark by fzf" },
  { on = [ "]", "d" ], run = "plugin whoosh delete_by_key", desc = "Delete bookmark by key" },
{ on = [ "]", "D" ], run = "plugin whoosh delete_by_fzf", desc = "Delete bookmarks by fzf (use TAB to select multiple)" },
  { on = [ "]", "C" ], run = "plugin whoosh delete_all", desc = "Delete all user bookmarks" },
  { on = [ "]", "r" ], run = "plugin whoosh rename_by_key", desc = "Rename bookmark by key" },
  { on = [ "]", "R" ], run = "plugin whoosh rename_by_fzf", desc = "Rename bookmark by fzf" },

]
