[services.rpi]
type     = "sftp"
host     = "100.95.254.47"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"

[services.mac]
type     = "sftp"
host     = "100.89.192.48"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"

[services.mini]
type     = "sftp"
host     = "100.123.155.110"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"

[services.work]
type     = "sftp"
host     = "100.103.198.13"
user     = "nurlan"
port     = 22
key_file = "~/.ssh/id_ed25519"
