[mgr]
ratio = [1,3,4] 
[plugin]
prepend_previewers = [
  { mime = "application/msword", run = 'piper -- antiword "$1"' },
  { url = "*.md",     run = 'piper -- leaf --inline "$1"' },
  { url = "*.docx",   run = 'piper -- doxx --export text "$1"' },
  { url = "*.{xlsx,xls,xlsm,xlsb,ods}", run = 'piper -- xleak "$1"' },
  { url = "*.tar*",   run = 'piper -- tar tf "$1"' },
  { url = "*.txt.gz", run = 'piper -- gzip -dc "$1"' },
  { url = '*.typ', run = 'preview-typst' },
]

